[package]
name = "kinject"
version = "0.1.1"
edition = "2021"

[dependencies]
# Adicione aqui as dependências necessárias para o seu projeto

[dev-dependencies]
# Adicione aqui as dependências de desenvolvimento, se necessário

[lib]
crate-type = ["cdylib", "rlib"]
